mod prob_1108_defanging_an_ip_address;
mod prob_1281_subtract_the_product_and_sum_of_digits_of_an_integer;
mod prob_1313_decompress_run_length_encoded_list;
mod prob_1365_how_many_numbers_are_smaller_than_the_current_number;
mod prob_1431_kids_with_greatest_num_of_candies;
mod prob_1470_shuffle_the_array;
mod prob_1480_running_sum_of_1d_array;
mod prob_1512_number_of_good_pairs;
mod prob_1672_richest_customer_wealth;
mod prob_1720_decode_xored_array;
mod prob_1920_build_array_from_permutation;
mod prob_1929_concatenation_of_array;
mod prob_2114_maximum_number_of_words_found_in_sentences;
mod prob_2160_minimum_sum_of_four_digit_number;
mod prob_771_jewels_and_stones;
fn main() {
    print!("Hello, World!");
}
